spring:
  application:
    name: enterprise-idp

  config:
    import: classpath:users.yaml

  datasource:
    url: jdbc:h2:mem:idp-test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 9080

client:
  url: http://localhost:8080

app:
  issuer-url: http://localhost:${server.port}
  authorizationConsent: true

  jwt:
    key-store: classpath:idp-keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: idp-signing
    key-password: changeit

oauth2:
  client-id: oidc-client
  client-secret: secret
  redirect-url-client: ${client.url}/login/oauth2/code/${oauth2.client-id}
  redirect-url-test: https://oauth.pstmn.io/v1/callback
  post-logout-redirect-url: ${client.url}/

logging:
  level:
    root: INFO
    com.idp: INFO
