spring:
  application:
    name: developer-idp

  config:
    import:
      - classpath:config-idp.yml
      - classpath:config-oauth2-client.yml
      - classpath:config-users.yml

  datasource:
    url: jdbc:h2:mem:idp-test;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

server:
  port: 9080

logging:
  level:
    root: INFO
    com.idp: INFO
    org.atmosphere: ERROR
