authorization-server:
  issuer-url: http://localhost:${server.port}
  authorization-consent: true
  access-token-ttl: 5m
  refresh-token-ttl: 30d
  authorization-code-ttl: 5m
  reuse-refresh-tokens: false
  supported-scopes: [openid, profile, email, address, phone]
  free-login: true

jwt:
  key-store: classpath:idp-keystore.p12
  key-store-type: PKCS12
  key-store-password: changeit
  key-alias: idp-signing
  key-password: changeit

claims:
  always:
    roles: roles
    groups: groups
  scopes:
    - scope: profile
      mappings:
        name: fullName
        given_name: firstName
        family_name: lastName
        preferred_username: username
    - scope: email
      mappings:
        email: email
        email_verified: emailVerified
    - scope: address
      mappings:
        address: address
    - scope: phone
      mappings:
        phone_number: phoneNumber
