oauth2-client:
  client-url: http://localhost:8080
  client-id: oidc-client
  client-secret: secret
  redirect-uris:
    - ${oauth2-client.client-url}/login/oauth2/code/${oauth2-client.client-id}
    - https://oauth.pstmn.io/v1/callback
  post-logout-redirect-uris:
    - ${oauth2-client.client-url}/
  scopes: [openid, profile, email, address, phone]
  authorization-grant-types: [authorization_code, refresh_token, client_credentials]
