oauth2-clients:
  - client-id: oidc-client
    client-secret: secret
    description: client test di default
    client-url: http://localhost:8080
    client-authentication-methods: [client_secret_basic]
    redirect-uris:
      - http://localhost:8080/login/oauth2/code/oidc-client
      - https://oauth.pstmn.io/v1/callback
    post-logout-redirect-uris:
      - http://localhost:8080/
    scopes: [openid, profile, email, address, phone]
    authorization-grant-types: [authorization_code, refresh_token, client_credentials]
    authorization-consent: true
    require-proof-key: true
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false

  - client-id: test-client
    client-secret: test-secret
    description: secondo client test
    client-url: http://localhost:8081
    client-authentication-methods: [client_secret_basic]
    redirect-uris:
      - http://localhost:8081/login/oauth2/code/test-client
    post-logout-redirect-uris:
      - http://localhost:8081/
    scopes: [openid, profile, email]
    authorization-grant-types: [authorization_code, client_credentials]
    authorization-consent: true
    require-proof-key: false
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false

  - client-id: public-client
    client-secret:
    client-url: http://localhost:8082
    description: client test pubblico
    client-authentication-methods: [none]
    redirect-uris:
      - http://localhost:8082/login/oauth2/code/public-client
    post-logout-redirect-uris:
      - http://localhost:8082/
    scopes: [openid, profile, email]
    authorization-grant-types: [authorization_code]
    authorization-consent: true
    require-proof-key: true
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false