oauth2-clients:
  first-client:
    client-url: http://localhost:8080
    client-id: oidc-client
    client-secret: secret
    client-authentication-methods: [client_secret_basic]
    redirect-uris:
      - ${oauth2-clients.first-client.client-url}/login/oauth2/code/${oauth2-clients.first-client.client-id}
      - https://oauth.pstmn.io/v1/callback
    post-logout-redirect-uris:
      - ${oauth2-clients.first-client.client-url}/
    scopes: [openid, profile, email, address, phone]
    authorization-grant-types: [authorization_code, refresh_token, client_credentials]
    authorization-consent: true
    require-proof-key: true
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false

  second-client:
    client-url: http://localhost:8081
    client-id: test-client
    client-secret: test-secret
    client-authentication-methods: [client_secret_basic]
    redirect-uris:
      - ${oauth2-clients.second-client.client-url}/login/oauth2/code/${oauth2-clients.second-client.client-id}
    post-logout-redirect-uris:
      - ${oauth2-clients.second-client.client-url}/
    scopes: [openid, profile, email]
    authorization-grant-types: [authorization_code, client_credentials]
    authorization-consent: true
    require-proof-key: false
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false

  third-client:
    client-url: http://localhost:8082
    client-id: public-client
    client-secret:
    client-authentication-methods: [none]
    redirect-uris:
      - ${oauth2-clients.third-client.client-url}/login/oauth2/code/${oauth2-clients.third-client.client-id}
    post-logout-redirect-uris:
      - ${oauth2-clients.third-client.client-url}/
    scopes: [openid, profile, email]
    authorization-grant-types: [authorization_code]
    authorization-consent: true
    require-proof-key: true
    access-token-ttl: 5m
    refresh-token-ttl: 30d
    authorization-code-ttl: 5m
    reuse-refresh-tokens: false
