authorization-server:
  issuer-url: http://localhost:${server.port}
  supported-scopes: [openid, profile, email, address, phone]
  supported-grant-types: [authorization_code, refresh_token, client_credentials]
  free-login: true

jwt:
  key-store: classpath:idp-keystore.p12
  key-store-type: PKCS12
  key-store-password: changeit
  key-alias: idp-signing
  key-password: changeit

claims:
  always:
    roles: roles
    groups: groups

  scopes:
    profile:
      name: fullName
      given_name: firstName
      family_name: lastName
      preferred_username: username

    email:
      email: email
      email_verified: emailVerified

    address:
      address: address

    phone:
      phone_number: phoneNumber
